meta_title: "Adrien Liagre"
meta_description: "Etudiant à l'EDHEC"
meta_image: "adrienliagre.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@L_ASdrI" # indispensable pour les Twitter Cards
